### ISSUE TITLE
user_types are lacking fields

### ISSUE THREAD

**Issue by farproc** [volatilityfoundation/dwarf2json#17]
The latest commit (72ea0337ac405c91943b8277c2a907bcdf85f114) prevents strucutres fields being populated. master~1 works as expected.

dwarf2json linux --elf ./vmlinux  # from http://ddebs.ubuntu.com/pool/main/l/linux/linux-image-unsigned-4.15.0-108-generic-dbgsym_4.15.0-108.109_amd64.ddeb

**Comment by ilch1** [comment]
Hi @farproc,

Thanks for reporting the issue and sorry for the delay! It should be fixed in the latest master. Please re-open the issue if the fix does not work as you expect.
