### ISSUE TITLE
d.AddSection undefined (type *dwarf.Data has no field or method AddSection)

### ISSUE THREAD

**Issue by tklengyel** [volatilityfoundation/dwarf2json#34]
Trying to build the latest master branch results in the error
```
./dwarf.go:108:15: d.AddSection undefined (type *dwarf.Data has no field or method AddSection)

**Comment by tklengyel** [comment]
Regression seems to be caused by e5104ad66cccbe3bc5cae502236d814d9f3e9f33

**Comment by npetroni** [comment]
Builds fine for me using Go 1.14 and Go 1.15. Can you provide more details?

Thanks

**Comment by tklengyel** [comment]
`go version go1.13.8 linux/amd64`, installed on a stock Ubuntu 20.04.

**Comment by cstation** [comment]
[AddSection](https://golang.org/pkg/debug/dwarf/#Data.AddSection) is added in Go 1.14 ([changelog](https://golang.org/doc/go1.14)), thus breaking `dwarf2json`'s compatibility with Go 1.13.

**Comment by npetroni** [comment]
Cool, thanks. 1.13 is not maintained anymore so we will update our docs. Build is passing with 1.15.
