### ISSUE TITLE
go.mod: checksum mismatch

### ISSUE THREAD

**Issue by Monrava** [volatilityfoundation/dwarf2json#40]
I encountered this error today when trying to install dwarf2json:

dwarf2json# go build
verifying github.com/spf13/pflag@v1.0.5/go.mod: checksum mismatch
	downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
	go.sum:     h1:McXfInJRrz4CZXVZOBLb0bTZqETkiAhM9Iw0y3An2Bg=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by ilch1** [comment]
HI @Monrava, sorry you are having trouble building dwarf2json.

I'm not able to reproduce this. I ran the following commands:
```
$ git clone https://github.com/volatilityfoundation/dwarf2json
$ go build
go: downloading github.com/spf13/pflag v1.0.5
```

As can be seen by the output from `go build`, the `spf13/pflag` dependency was downloaded.

You could try cleaning your local mod cache with `go clean -modcache` and then rebuilding.

**Comment by Monrava** [comment]
Hi ilch1.

This fixed the issue.
Thank you!
