### ISSUE TITLE
struct name lost?

### ISSUE THREAD

**Issue by diguasange** [volatilityfoundation/dwarf2json#43]
when struct defined in this style:
tyedef struct{
...
}aaa;
aaa bbb;
The output json will not contain the name "aaa", just show unamed_xxxx. So the json can output the real  struct name directly?
output such as:
"bbb": {
  "type": {
    "kind": "struct",
    "name": "aaa"
  },
  "offset": 7
}

**Comment by mkonshie** [comment]
This issue should be resolved by this commit: 9b43eb8fc85b7b2851485fadea30fd4213bfc57b 

Closing this issue, feel free to open it back up if the issue persists.
