### ISSUE TITLE
unknown ELF version 'EV_NONE' in record at byte 0x0

### ISSUE THREAD

**Issue by aleff-github** [volatilityfoundation/dwarf2json#47]
Hi Dear,
- I have cloned the tool
- then, I did `go build`
- then, sent the command `.\dwarf2json.exe linux --elf C:/Users/User/Dumps/mem.elf > output.json`

and i received this error:
```
Failed linux processing: could not open C:/Users/User/Dumps/mem.elf: unknown ELF version 'EV_NONE' in record at byte 0x0
```

What can be the problem?

**Comment by ilch1** [comment]
Hey @aleff-github,

It appears you are passing an actual memory sample in elf format to dwarf2json. The dwarf2json tool is meant to convert DWARF information contained in an ELF to an ISF file json file. The memory sample can be analyzed with volatility3.

Thanks
