### ISSUE TITLE
Bitfield with negative bit_position value

### ISSUE THREAD

**Issue by IridiumXOR** [volatilityfoundation/dwarf2json#49]
Hi,
generating the json profile for vmlinux-5.19.0-40-generic Ubuntu 22.04 stock kernel I have discovered that the tool produce a negative ```bit_position``` value for bitfields (example for field ```active_mode``` in ```struct Scsi_Host```.
I think the problem come from this line: 
https://github.com/volatilityfoundation/dwarf2json/blob/c306d1132f014dc882ffc0ad22e97764bae49451/main.go#L290

Please can you fix it?

**Comment by Shiselster** [comment]
I tend to believe the issue stems from differences between DWARF Version 4 and DWARF Version 5, the latter probably not supported by dwarf2json yet?

**Comment by Shiselster** [comment]
Issue seems to be fixed after commit https://github.com/volatilityfoundation/dwarf2json/pull/58/commits/9673739daf497a6ebc835f6dcb8f74de19d9e8ba!!

Great job @mkonshie!
Any plans to merge https://github.com/volatilityfoundation/dwarf2json/pull/58 back into master?
